### PR TITLE
Add CI using GitHub Actions

### PR DESCRIPTION
**Pull request by tmm1**
This will run all the tests for new PRs to ensure there are no regressions

### CODE REVIEW

**Comment by tmm1** [comment]
Hmm, I thought before there was no CI but maybe travis CI was really backed up and didn't report back on my PRs when I was looking...

**Comment by asticode** [comment]
I've never used Github actions, therefore out of curiosity, would you say it's "better" than Travis? Why?

**Comment by tmm1** [comment]
I don't have a preference and feel like all the CI services are interchangeable.

TravisCI has announced that travis-ci.org will be shutting down. It's unclear when that is going to happen, and what steps will be required to move CI to travis-ci.com

I noticed that TravisCI is set up to run coverage as well. I missed that before so that's something that would need to be copied over into the GitHub action.

**Comment by aler9** [comment]
This has been implemented in 0df190a, therefore this PR can be closed.

**Comment by asticode** [comment]
👍

**Pull request closed without merging**
